import type { Exercise } from "@/types/exercise";

export const MOCK_EXERCISES: Exercise[] = [
  {
    id: "squat",
    label: "Squat",
    icon: "🦵",
    target: "Knee & Hip Rehab",
    type: "physio",
    video_id: "YaXPRqUwItQ",
    form_checks: ["Back angle", "Knees over toes", "Spine"],
    tip: "Stand shoulder-width apart, keep chest up!",
    limitations: ["knee_pain", "hip_pain"],
    difficulty: "moderate",
    recommended_reps: 10,
    description: "A fundamental lower body exercise targeting the quadriceps, hamstrings, and glutes. Essential for knee and hip rehabilitation.",
  },
  {
    id: "shoulder_raises",
    label: "Shoulder Raises",
    icon: "💪",
    target: "Shoulder Rehab",
    type: "physio",
    video_id: "FeGNSMVFBHg",
    form_checks: ["Arms straight", "Height control", "Spine"],
    tip: "Move slowly and in control — no swinging!",
    limitations: ["shoulder_injury"],
    difficulty: "easy",
    recommended_reps: 10,
    description: "Lateral arm raises to strengthen the shoulder muscles and improve rotator cuff stability.",
  },
  {
    id: "crossover_arm_stretch",
    label: "Crossover Arm Stretch",
    icon: "🤸",
    target: "Shoulder Mobility",
    type: "physio",
    video_id: "5bMBCOgFHug",
    form_checks: ["No shrug", "Torso still"],
    tip: "Hold each stretch for a full 2 seconds!",
    limitations: ["shoulder_injury"],
    difficulty: "easy",
    recommended_reps: 10,
    description: "A cross-body shoulder stretch that improves flexibility and range of motion in the posterior shoulder.",
  },
  {
    id: "lateral_walks",
    label: "Lateral Walks",
    icon: "🚶",
    target: "Hip & Knee Rehab",
    type: "physio",
    video_id: "swFjPnGXFxk",
    form_checks: ["Knee bend", "Torso upright"],
    tip: "Stay low throughout — don't stand between steps!",
    limitations: ["knee_pain"],
    difficulty: "moderate",
    recommended_reps: 10,
    description: "Side-stepping exercise that activates hip abductors and improves lateral stability.",
  },
  {
    id: "lunges",
    label: "Lunges",
    icon: "🏃",
    target: "Leg Strength Rehab",
    type: "physio",
    video_id: "QOVaHwm-Q6U",
    form_checks: ["Knee alignment", "Torso", "Depth"],
    tip: "Keep front knee directly above ankle!",
    limitations: ["knee_pain", "hip_pain"],
    difficulty: "moderate",
    recommended_reps: 10,
    description: "Forward lunges that build single-leg strength, balance, and coordination.",
  },
  {
    id: "calf_raises",
    label: "Calf Raises",
    icon: "👟",
    target: "Ankle & Calf Rehab",
    type: "physio",
    video_id: "J0DnG1_S92I",
    form_checks: ["Legs straight", "No forward lean"],
    tip: "Lower heels ALL the way down each rep!",
    limitations: ["ankle_injury"],
    difficulty: "easy",
    recommended_reps: 15,
    description: "Standing calf raises to strengthen the gastrocnemius and soleus muscles for ankle stability.",
  },
  {
    id: "knee_raises",
    label: "Knee Raises",
    icon: "🦿",
    target: "Hip Flexor & Core",
    type: "physio",
    video_id: "RHrGLFDRRCY",
    form_checks: ["Back straight", "Height", "Control"],
    tip: "Engage your core — don't lean backward!",
    limitations: ["hip_pain"],
    difficulty: "easy",
    recommended_reps: 10,
    description: "Alternating knee raises that strengthen hip flexors and core stability.",
  },
  {
    id: "tree_pose",
    label: "Tree Pose",
    icon: "🌳",
    target: "Balance & Stability",
    type: "yoga",
    video_id: "wdln9qWYloU",
    form_checks: ["Spine straight", "No lean", "Balance"],
    tip: "Fix your gaze on one spot to help balance!",
    limitations: ["balance_issues"],
    difficulty: "moderate",
    recommended_reps: 5,
    description: "A standing balance pose that strengthens the legs, core, and improves overall stability.",
  },
  {
    id: "warrior_pose",
    label: "Warrior Pose",
    icon: "⚔️",
    target: "Leg & Core Strength",
    type: "yoga",
    video_id: "Mn6RSIRCV3w",
    form_checks: ["Torso upright", "Arms wide", "Knee bend"],
    tip: "Front knee tracks over front foot — not inward!",
    limitations: ["knee_pain", "hip_pain"],
    difficulty: "moderate",
    recommended_reps: 5,
    description: "A powerful standing pose that builds strength in the legs, opens the hips and chest.",
  },
  {
    id: "cat_cow_stretch",
    label: "Cat-Cow Stretch",
    icon: "🐄",
    target: "Spine Flexibility",
    type: "yoga",
    video_id: "kqnua4rHVVA",
    form_checks: ["Head position", "Full arch", "Full round"],
    tip: "Breathe in for cow, breathe out for cat!",
    limitations: ["back_pain"],
    difficulty: "easy",
    recommended_reps: 10,
    description: "A flowing spinal movement that improves flexibility and relieves back tension.",
  },
];
