"""password reset tokens and auth throttling

Revision ID: b0411f7bc699
Revises: c4c7db25443c
Create Date: 2026-09-14 22:55:32.106519
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0411f7bc699'
down_revision: Union[str, None] = 'c4c7db25443c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_throttles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_throttles')),
    sa.UniqueConstraint('scope', 'key', name='scope_key')
    )
    op.create_index(op.f('ix_auth_throttles_key'), 'auth_throttles', ['key'], unique=False)
    op.create_index(op.f('ix_auth_throttles_scope'), 'auth_throttles', ['scope'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('portal_role', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_password_reset_tokens_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_account_id'), 'password_reset_tokens', ['account_id'], unique=False)

    # ``token_version`` is added as NOT NULL. Every existing row needs a value, so
    # the column is created with a server-side default. Without it this statement
    # fails on any database that already contains accounts - which is exactly the
    # case when upgrading a live install, and the reason this migration used to
    # be unusable outside a freshly created database.
    op.add_column(
        'accounts',
        sa.Column('token_version', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    # Belt and braces for a database that partially applied an earlier revision.
    op.execute('UPDATE accounts SET token_version = 0 WHERE token_version IS NULL')

    if op.get_bind().dialect.name == 'postgresql':
        # Drop the temporary default so the schema matches the model, which
        # supplies the value from Python. On SQLite this would require a full
        # table rebuild (and rewriting the foreign keys that reference
        # ``accounts``); that is a larger risk than the harmless default it would
        # remove, so the default is deliberately retained there.
        op.alter_column('accounts', 'token_version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'token_version')
    op.drop_index(op.f('ix_password_reset_tokens_account_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_auth_throttles_scope'), table_name='auth_throttles')
    op.drop_index(op.f('ix_auth_throttles_key'), table_name='auth_throttles')
    op.drop_table('auth_throttles')
    # ### end Alembic commands ###
