"""initial schema

Revision ID: c4c7db25443c
Revises: 
Create Date: 2026-09-14 22:36:01.383737
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4c7db25443c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('patient', 'doctor')", name=op.f('ck_accounts_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_role'), 'accounts', ['role'], unique=False)
    op.create_table('diet_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_diet_records_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_records'))
    )
    op.create_index(op.f('ix_diet_records_patient_account_id'), 'diet_records', ['patient_account_id'], unique=False)
    op.create_index(op.f('ix_diet_records_recorded_at'), 'diet_records', ['recorded_at'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('available_days', sa.String(length=120), nullable=False),
    sa.Column('timings', sa.String(length=120), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hospital', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_doctor_profiles_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_profiles')),
    sa.UniqueConstraint('account_id', name=op.f('uq_doctor_profiles_account_id'))
    )
    op.create_table('guardian_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_to', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_guardian_alerts_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardian_alerts'))
    )
    op.create_index(op.f('ix_guardian_alerts_patient_account_id'), 'guardian_alerts', ['patient_account_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=False),
    sa.Column('current_problem', sa.Text(), nullable=False),
    sa.Column('problem_start_date', sa.String(length=30), nullable=False),
    sa.Column('problem_cause', sa.Text(), nullable=False),
    sa.Column('previous_injuries', sa.Text(), nullable=False),
    sa.Column('past_surgeries', sa.Text(), nullable=False),
    sa.Column('medical_conditions', sa.Text(), nullable=False),
    sa.Column('current_medications', sa.Text(), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=False),
    sa.Column('precautions', sa.Text(), nullable=False),
    sa.Column('exercise_limitations', sa.Text(), nullable=False),
    sa.Column('pain_location', sa.String(length=255), nullable=False),
    sa.Column('pain_intensity', sa.Integer(), nullable=False),
    sa.Column('pain_type', sa.String(length=120), nullable=False),
    sa.Column('pain_triggers', sa.Text(), nullable=False),
    sa.Column('pain_duration', sa.String(length=120), nullable=False),
    sa.Column('daily_sitting_hours', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=120), nullable=False),
    sa.Column('exercise_habits', sa.Text(), nullable=False),
    sa.Column('movement_restrictions', sa.Text(), nullable=False),
    sa.Column('rehab_goals', sa.Text(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=False),
    sa.Column('guardian_whatsapp', sa.String(length=50), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_patient_profiles_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profiles')),
    sa.UniqueConstraint('account_id', name=op.f('uq_patient_profiles_account_id'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('month_name', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_reports_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_patient_account_id'), 'reports', ['patient_account_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=120), nullable=False),
    sa.Column('exercise_label', sa.String(length=255), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('form_accuracy', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_workout_sessions_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions'))
    )
    op.create_index(op.f('ix_workout_sessions_patient_account_id'), 'workout_sessions', ['patient_account_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_performed_at'), 'workout_sessions', ['performed_at'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('time', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('clinician_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], name=op.f('fk_appointments_doctor_profile_id_doctor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_appointments_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_doctor_profile_id'), 'appointments', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_account_id'), 'appointments', ['patient_account_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('doctor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], name=op.f('fk_doctor_notes_doctor_profile_id_doctor_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_doctor_notes_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_notes'))
    )
    op.create_index(op.f('ix_doctor_notes_doctor_profile_id'), 'doctor_notes', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_doctor_notes_patient_account_id'), 'doctor_notes', ['patient_account_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], name=op.f('fk_messages_doctor_profile_id_doctor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_messages_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_doctor_profile_id'), 'messages', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_messages_patient_account_id'), 'messages', ['patient_account_id'], unique=False)
    op.create_table('patient_doctor_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], name=op.f('fk_patient_doctor_links_doctor_profile_id_doctor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_account_id'], ['accounts.id'], name=op.f('fk_patient_doctor_links_patient_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_doctor_links')),
    sa.UniqueConstraint('patient_account_id', 'doctor_profile_id', name='patient_doctor')
    )
    op.create_index(op.f('ix_patient_doctor_links_doctor_profile_id'), 'patient_doctor_links', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_patient_doctor_links_patient_account_id'), 'patient_doctor_links', ['patient_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_doctor_links_patient_account_id'), table_name='patient_doctor_links')
    op.drop_index(op.f('ix_patient_doctor_links_doctor_profile_id'), table_name='patient_doctor_links')
    op.drop_table('patient_doctor_links')
    op.drop_index(op.f('ix_messages_patient_account_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_doctor_profile_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_doctor_notes_patient_account_id'), table_name='doctor_notes')
    op.drop_index(op.f('ix_doctor_notes_doctor_profile_id'), table_name='doctor_notes')
    op.drop_table('doctor_notes')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_account_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_profile_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_workout_sessions_performed_at'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_patient_account_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_reports_patient_account_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_guardian_alerts_patient_account_id'), table_name='guardian_alerts')
    op.drop_table('guardian_alerts')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_diet_records_recorded_at'), table_name='diet_records')
    op.drop_index(op.f('ix_diet_records_patient_account_id'), table_name='diet_records')
    op.drop_table('diet_records')
    op.drop_index(op.f('ix_accounts_role'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
